In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('./proyecto_superstore_sindup_Id.csv',encoding='ISO-8859-1')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,ship_ID,Category_ID,City_ID
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,1,1,1
1,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,1,2,2
2,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2,1,3
3,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694,2,1,2
4,13,CA-2017-114412,4/15/2017,4/20/2017,Standard Class,AA-10480,Andrew Allen,Consumer,United States,Concord,...,Office Supplies,Paper,Xerox 1967,15.5520,3,0.20,5.4432,2,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5004,9987,CA-2016-125794,9/29/2016,10/3/2016,Standard Class,ML-17410,Maris LaWare,Consumer,United States,Los Angeles,...,Technology,Accessories,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,36.2400,1,0.00,15.2208,2,3,2
5005,9988,CA-2017-163629,11/17/2017,11/21/2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,Technology,Accessories,Logitech G430 Surround Sound Gaming Headset wi...,79.9900,1,0.00,28.7964,2,3,418
5006,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,1,1,101
5007,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,2,1,117
5008,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,1,2,224

In [4]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'ship_ID',
       'Category_ID', 'City_ID'],
      dtype='object')

In [5]:
nuevos_nombres = {
    'Order ID': 'Order_ID',
    'Row ID': 'Row_ID',
    'Customer ID': 'Customer_ID',
    'Product ID': 'Product_ID',
    '': '',
    
}

df.rename(columns=nuevos_nombres, inplace=True)

In [6]:
df.columns

Index(['Row_ID', 'Order_ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer_ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product_ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'ship_ID',
       'Category_ID', 'City_ID'],
      dtype='object')

In [7]:
fact_sales_mstr = ['Row_ID','Order_ID','Customer_ID','Product_ID','ship_ID','Category_ID', 'City_ID','Sales', 'Quantity', 'Discount', 'Profit']

In [8]:
fact_sales_mstr = df[fact_sales_mstr].copy()

In [9]:
fact_sales_mstr.to_csv('fact_sales_mstr.csv', index=False)

In [10]:
df_fact = pd.read_csv('./fact_sales_mstr.csv', encoding='utf-8', engine='python')
df_fact

,Row_ID,Order_ID,Customer_ID,Product_ID,ship_ID,Category_ID,City_ID,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,CG-12520,FUR-BO-10001798,1,1,1,261.9600,2,0.00,41.9136
1,3,CA-2016-138688,DV-13045,OFF-LA-10000240,1,2,2,14.6200,2,0.00,6.8714
2,4,US-2015-108966,SO-20335,FUR-TA-10000577,2,1,3,957.5775,5,0.45,-383.0310
3,6,CA-2014-115812,BH-11710,FUR-FU-10001487,2,1,2,48.8600,7,0.00,14.1694
4,13,CA-2017-114412,AA-10480,OFF-PA-10002365,2,2,4,15.5520,3,0.20,5.4432
...,...,...,...,...,...,...,...,...,...,...,...
5004,9987,CA-2016-125794,ML-17410,TEC-AC-10003399,2,3,2,36.2400,1,0.00,15.2208
5005,9988,CA-2017-163629,RA-19885,TEC-AC-10001539,2,3,418,79.9900,1,0.00,28.7964
5006,9990,CA-2014-110422,TB-21400,FUR-FU-10001889,1,1,101,25.2480,3,0.20,4.1028
5007,9991,CA-2017-121258,DB-13060,FUR-FU-10000747,2,1,117,91.9600,2,0.00,15.6332
5008,9994,CA-2017-119914,CC-12220,OFF-AP-10002684,1,2,224,243.1600,2,0.00,72.9480